FROM openjdk:17-alpine

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

ARG JAR_FILE=build/libs/game-server-1.0.0.jar
COPY ${JAR_FILE} /app/game-server.jar

RUN chown -R appuser:appgroup /app

USER appuser

ENTRYPOINT ["java","-Xms512m", "-Xmx512m", "-jar", "/app/game-server.jar"]