logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  r2dbc:
    url: r2dbc:mysql://localhost:3306/slime?serverZoneId=UTC
    username: root
    password: "1234"
    pool:
      max-size: 50
      validation-query: "SELECT 1"
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      match-queue-key: multi_match_queue

kafka:
  ip: ${KAFKA_IP}
  port: ${KAFKA_PORT}
  topic:
    match-start: match-start
    player-move: player-move

server:
  ip: localhost
  port: 8080

