logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri:  http://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
---
spring:
  config:
    activate:
      on-profile: local

  r2dbc:
    url: r2dbc:mysql://localhost:3306/slime?serverZoneId=UTC
    username: root
    password: "1234"
    pool:
      max-size: 50
      validation-query: "SELECT 1"
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      match-queue-key: multi_match_queue

kafka:
  ip: ${KAFKA_IP}
  port: ${KAFKA_PORT}
  topic:
    match-start: match-start
    player-move: player-move

server:
  ip: localhost
  port: 8080